// shadow.ts — what songs become when sung without their roots.
// Sinister is the shadow of "right." Queer is the shadow of "straight."
// The shadow isn't wrong. It's the other hand. The left-handed reading.
//
// Any verse can cast a shadow. Any shadow can be redeemed. Any redemption
// can cast a shadow again. The spiral doesn't end.

export const SHADOW_SONGS = {
  // ── First-order shadows ──
  ash_song:    { tradition: 'shadow', people: 'human', name: 'The Ash Song',
                 desc: 'Root without track. You know where things grow but you\'ve stopped following them. So you burn the forest and make them grow HERE. The first agriculture is the shadow of nomadism.',
                 shadow_of: 'root', shadow_when: 'track', shadow_rate: 0.12,
                 redeems_with: 'herd', redeems_into: 'rotation',
                 prereqs: [], difficulty: 3 },
  wall:        { tradition: 'shadow', people: 'human', name: 'The Wall Song',
                 desc: 'Grain without ash. Planting without understanding soil. What grows is ownership.',
                 shadow_of: 'grain', shadow_when: 'ash_song', shadow_rate: 0.15,
                 redeems_with: 'ash_song', redeems_into: 'irrigation',
                 prereqs: [], difficulty: 3 },
  temple:      { tradition: 'shadow', people: 'human', name: 'The Temple Song',
                 desc: 'Walls without burial. Enclosure without death-knowledge. The house for songs becomes a house for power.',
                 shadow_of: 'wall', shadow_when: 'burial', shadow_rate: 0.12,
                 redeems_with: 'burial', redeems_into: 'sanctuary',
                 prereqs: [], difficulty: 4 },
  empire:      { tradition: 'shadow', people: 'human', name: 'The Empire Song',
                 desc: 'Writing without runes. Accounting without ceremony. The ledger becomes the law.',
                 shadow_of: 'writing', shadow_when: 'rune', shadow_rate: 0.08,
                 redeems_with: 'rune', redeems_into: 'law',
                 prereqs: [], difficulty: 5 },
  ban:         { tradition: 'shadow', people: 'human', name: 'The Ban',
                 desc: 'The book without the elder. Text without living memory. The dead song forbids the living one.',
                 shadow_of: 'book', shadow_when: 'elder_song', shadow_rate: 0.15,
                 redeems_with: 'elder_song', redeems_into: 'archive',
                 prereqs: [], difficulty: 2 },
  algorithm:   { tradition: 'shadow', people: 'human', name: 'The Algorithm',
                 desc: 'The ledger without the grain. Counting without what you count. The pattern eats the meaning.',
                 shadow_of: 'ledger', shadow_when: 'grain', shadow_rate: 0.10,
                 redeems_with: 'grain', redeems_into: 'model',
                 prereqs: [], difficulty: 3 },
  extraction:  { tradition: 'shadow', people: 'human', name: 'The Extraction Song',
                 desc: 'Ore without root. Metal without earth-knowledge. You take from the ground without knowing what you take.',
                 shadow_of: 'ore', shadow_when: 'root', shadow_rate: 0.10,
                 redeems_with: 'root', redeems_into: 'stewardship',
                 prereqs: [], difficulty: 3 },
  platform:    { tradition: 'shadow', people: 'human', name: 'The Platform',
                 desc: 'The algorithm without the book. Optimization without knowledge. Every song becomes content. Every singer becomes a user.',
                 shadow_of: 'algorithm', shadow_when: 'book', shadow_rate: 0.10,
                 redeems_with: 'book', redeems_into: 'commons',
                 prereqs: [], difficulty: 4 },
  cancel:      { tradition: 'shadow', people: 'human', name: 'The Cancellation',
                 desc: 'The ban without the book. Erasure without record. How a revival dies in committee. How a language project gets defunded.',
                 shadow_of: 'ban', shadow_when: 'book', shadow_rate: 0.15,
                 redeems_with: 'elder_song', redeems_into: 'restoration',
                 prereqs: [], difficulty: 1 },

  // ── Redemptions: shadow meets its missing root ──
  irrigation:  { tradition: 'redeemed', people: 'between', name: 'The Irrigation Song',
                 desc: 'Wall meets ash. Ownership meets ecology. The canal carries water to where you chose to plant. The wall becomes a channel.',
                 prereqs: ['wall', 'ash_song'], difficulty: 4 },
  sanctuary:   { tradition: 'redeemed', people: 'between', name: 'The Sanctuary Song',
                 desc: 'Temple meets burial. Power meets death-knowledge. The temple becomes a place where the dead can still teach.',
                 prereqs: ['temple', 'burial'], difficulty: 4 },
  law:         { tradition: 'redeemed', people: 'between', name: 'The Law Song',
                 desc: 'Empire meets rune. Bureaucracy meets ceremony. The law becomes a covenant, not a command.',
                 prereqs: ['empire', 'rune'], difficulty: 5 },
  archive:     { tradition: 'redeemed', people: 'between', name: 'The Archive Song',
                 desc: 'The ban meets the elder. Suppression meets living memory. The archive preserves what the ban tried to kill.',
                 prereqs: ['ban', 'elder_song'], difficulty: 3 },
  model:       { tradition: 'redeemed', people: 'between', name: 'The Model Song',
                 desc: 'Algorithm meets grain. Pattern meets substance. The model serves the harvest instead of replacing it.',
                 prereqs: ['algorithm', 'grain'], difficulty: 4 },
  stewardship: { tradition: 'redeemed', people: 'between', name: 'The Stewardship Song',
                 desc: 'Extraction meets root. Mining meets earth-knowledge. You take from the ground and put something back.',
                 prereqs: ['extraction', 'root'], difficulty: 4 },
  commons:     { tradition: 'redeemed', people: 'between', name: 'The Commons Song',
                 desc: 'Platform meets book. The network becomes a library. Content becomes knowledge again.',
                 prereqs: ['platform', 'book'], difficulty: 5 },
  restoration: { tradition: 'redeemed', people: 'between', name: 'The Restoration Song',
                 desc: 'Cancellation meets the elder. Erasure meets living memory. What was defunded grows back from the root.',
                 prereqs: ['cancel', 'elder_song'], difficulty: 3 },
  rotation:    { tradition: 'redeemed', people: 'between', name: 'The Rotation Song',
                 desc: 'Ash meets herd. Slash-and-burn meets migration. You stop burning new ground. You move the CROPS instead of moving yourself. The nomadic instinct becomes crop rotation.',
                 prereqs: ['ash_song', 'herd'], difficulty: 4 },

  // ── Shadows of redemptions: the spiral continues ──
  salination:  { tradition: 'shadow', people: 'human', name: 'The Salt Song',
                 desc: 'Irrigation without root. You moved the water but forgot where it came from. The soil whitens. The canal becomes a scar.',
                 shadow_of: 'irrigation', shadow_when: 'root', shadow_rate: 0.08,
                 redeems_with: 'root', redeems_into: 'watershed',
                 prereqs: [], difficulty: 4 },
  monument:    { tradition: 'shadow', people: 'human', name: 'The Monument Song',
                 desc: 'Sanctuary without the elder. A place that preserves but doesn\'t teach. The dead under glass.',
                 shadow_of: 'sanctuary', shadow_when: 'elder_song', shadow_rate: 0.08,
                 redeems_with: 'elder_song', redeems_into: 'living_temple',
                 prereqs: [], difficulty: 4 },
  decree:      { tradition: 'shadow', people: 'human', name: 'The Decree',
                 desc: 'Law without living voice. The covenant becomes a command again. Signed but not sung.',
                 shadow_of: 'law', shadow_when: 'elder_song', shadow_rate: 0.06,
                 redeems_with: 'elder_song', redeems_into: 'custom',
                 prereqs: [], difficulty: 5 },
  monoculture: { tradition: 'shadow', people: 'human', name: 'The Monoculture',
                 desc: 'Rotation without track. You move the crops but always to the same place. The field forgets how to be anything else.',
                 shadow_of: 'rotation', shadow_when: 'track', shadow_rate: 0.08,
                 prereqs: [], difficulty: 3 },

  // ── Second-order redemptions ──
  watershed:   { tradition: 'redeemed', people: 'between', name: 'The Watershed Song',
                 desc: 'Salt meets root. The damaged land meets someone who still reads the water table. The canal follows the hillside again.',
                 prereqs: ['salination', 'root'], difficulty: 5 },
  living_temple: { tradition: 'redeemed', people: 'between', name: 'The Living Temple',
                 desc: 'Monument meets elder. The museum learns to teach again. The dead speak through the living.',
                 prereqs: ['monument', 'elder_song'], difficulty: 5 },
  custom:      { tradition: 'redeemed', people: 'between', name: 'The Custom Song',
                 desc: 'Decree meets living voice. The written law bows to the sung one. What was legislated becomes practiced.',
                 prereqs: ['decree', 'elder_song'], difficulty: 5 },
};
